-- 코드를 입력하세요
 WITH 
 CTE AS (
     SELECT
    a.CAR_ID,a.CAR_TYPE,a.DAILY_FEE,b.START_DATE,b.END_DATE
FROM
    CAR_RENTAL_COMPANY_CAR a
JOIN
   CAR_RENTAL_COMPANY_RENTAL_HISTORY b
ON 
    a.CAR_ID = b.CAR_ID
WHERE
    CAR_TYPE in ('세단','SUV')
GROUP BY
    a.CAR_ID,a.CAR_TYPE
HAVING
    MAX(b.START_DATE) not Between '2022-11-01' and '2022-11-30'
AND
    MAX(b.END_DATE) < '2022-11-01'
),
CTE2 as (
SELECT 
    CAR_TYPE,DISCOUNT_RATE 
FROM
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
WHERE
    DURATION_TYPE = '30일 이상'
    AND
    CAR_TYPE in ('세단','SUV')
)
SELECT
    a.CAR_ID,a.CAR_TYPE,ROUND((a.DAILY_FEE - (a.DAILY_FEE * DISCOUNT_RATE/100))*30) as FEE
FROM
    CTE a
JOIN
    CTE2 b
ON
    a.CAR_TYPE = b.CAR_TYPE
WHERE 
    ROUND(a.DAILY_FEE - (a.DAILY_FEE * DISCOUNT_RATE/100))*30 BETWEEN 500000 and 2000000
ORDER BY
    FEE DESC,a.CAR_TYPE,a.CAR_ID