-- 코드를 입력하세요
SELECT
    a.ANIMAL_ID,a.ANIMAL_TYPE,a.NAME
FROM
    ANIMAL_OUTS a
JOIN
    (SELECT ANIMAL_ID FROM ANIMAL_INS 
     WHERE SEX_UPON_INTAKE like 'Intact%') as b
ON 
    a.ANIMAL_ID = b.ANIMAL_ID
WHERE
    SEX_UPON_OUTCOME not like 'Intact%'