-- 코드를 입력하세요
WITH CTE as (
SELECT 
    SHIPMENT_ID,FLAVOR,SUM(TOTAL_ORDER) as TOTAL_ORDER
FROM
    JULY
GROUP BY 
    FLAVOR
HAVING
    SHIPMENT_ID IN (SELECT SHIPMENT_ID  FROM FIRST_HALF)
)
SELECT 
   a.FLAVOR
FROM
    FIRST_HALF a
JOIN
    CTE b
ON
    a.SHIPMENT_ID = b.SHIPMENT_ID
ORDER BY b.TOTAL_ORDER+a.TOTAL_ORDER desc
LIMIT 3