-- 코드를 입력하세요
SELECT
a.USER_ID,a.NICKNAME,SUM(b.PRICE) as TOTAL_SALES
FROM
USED_GOODS_USER a
JOIN USED_GOODS_BOARD b
ON a.USER_ID = b.WRITER_ID
WHERE b.STATUS = 'DONE'
GROUP BY a.USER_ID,a.NICKNAME
HAVING TOTAL_SALES >= 700000
ORDER BY 
TOTAL_SALES