-- 코드를 입력하세요
SELECT
b.MEMBER_NAME,a.REVIEW_TEXT,DATE_FORMAT(a.REVIEW_DATE,'%Y-%m-%d') as REVIEW_DATE
FROM
MEMBER_PROFILE b
JOIN
(SELECT MEMBER_ID,REVIEW_TEXT,REVIEW_DATE FROM REST_REVIEW  WHERE MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
)) as a
ON a.MEMBER_ID = b.MEMBER_ID
ORDER BY REVIEW_DATE,REVIEW_TEXT