SELECT
    MONTH(START_DATE) as MONTH,
    CAR_ID,
    COUNT(CAR_ID) as RECORDS
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE
    CAR_ID in (SELECT CAR_ID
               FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
               WHERE  DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
               GROUP BY CAR_ID
               HAVING 
               COUNT(CAR_ID) >4
              )
    AND DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
GROUP BY
    CAR_ID,MONTH
HAVING
    RECORDS > 0 
ORDER BY
    MONTH,CAR_ID DESC