-- 코드를 입력하세요
SELECT
e.TITLE,e.BOARD_ID,d.REPLY_ID,d.WRITER_ID,d.CONTENTS,
DATE_FORMAT(d.CREATED_DATE,'%Y-%m-%d') as CREATED_DATE
FROM 
USED_GOODS_BOARD  e
JOIN USED_GOODS_REPLY d
ON e.BOARD_ID = d.BOARD_ID
WHERE e.CREATED_DATE like '2022-10%'
ORDER BY CREATED_DATE , e.TITLE