-- 코드를 입력하세요
SELECT
    CONCAT('/home/grep/src/',a.BOARD_ID,'/',a.FILE_ID,a.FILE_NAME,a.FILE_EXT) as FILE_PATH
FROM
    USED_GOODS_FILE a
WHERE
    BOARD_ID = (SELECT BOARD_ID FROM USED_GOODS_BOARD ORDER BY VIEWS DESC LIMIT 1) 
ORDER BY 
    FILE_ID DESC