-- 코드를 작성해주세요
WITH CTE as (
    SELECT 
    (
    CASE
    WHEN SKILL_CODE&(SELECT CODE FROM SKILLCODES WHERE NAME='Python') AND 
         (
         SKILL_CODE&(SELECT CODE FROM SKILLCODES WHERE NAME='JavaScript') OR
         SKILL_CODE&(SELECT CODE FROM SKILLCODES WHERE NAME='React') OR
         SKILL_CODE&(SELECT CODE FROM SKILLCODES WHERE NAME='Vue')
         )
       THEN 'A'
       WHEN
           SKILL_CODE&(SELECT CODE FROM SKILLCODES WHERE NAME='C#') THEN 'B' 
       WHEN
           SKILL_CODE&(SELECT CODE FROM SKILLCODES WHERE NAME='JavaScript') OR
           SKILL_CODE&(SELECT CODE FROM SKILLCODES WHERE NAME='React') OR
           SKILL_CODE&(SELECT CODE FROM SKILLCODES WHERE NAME='Vue')
           THEN 'C'   
       ELSE NULL
    END
   ) as GRADE,ID,EMAIL
FROM 
    DEVELOPERS
)
SELECT
    GRADE,ID,EMAIL
FROM
    CTE
WHERE
    GRADE is NOT NULL
ORDER BY 
    GRADE,ID

    
    